#!/usr/bin/env bash

set -e


# 如果没有 ARNOLD_WORKER_GPU 说明不是 arnold 的环境，
# 则按单机处理，并获取当前gpu数。
# 否则按arnold的环境变量来
gpu_num=$(lspci | grep -i NVIDIA | wc -l)
if [ -z $ARNOLD_WORKER_GPU ]; then
  echo "Not on Arnold env, find ${gpu_num} gpu"
  export ARNOLD_WORKER_NUM=1
  export ARNOLD_WORKER_GPU=$gpu_num
  export METIS_TASK_INDEX=0
  export METIS_WORKER_0_HOST=0.0.0.0
  export METIS_WORKER_0_PORT=8924
fi

echo "start launch tasks ..."
python3 -m fex.engine.launch \
    --nproc_per_node ${ARNOLD_WORKER_GPU} \
    --nnodes ${ARNOLD_WORKER_NUM} \
    --node_rank ${METIS_TASK_INDEX} \
    --master_addr ${METIS_WORKER_0_HOST} \
    --master_port ${METIS_WORKER_0_PORT} \
    $@ || exit 1

echo "finish training ..."
